### ISSUE TITLE
No podspec found...

### ISSUE THREAD

**Issue by gabrielmoncea** [stoneman1/ignite-firebase#23]
Hello, again,

I have this issue now when running `pod install`
```
Analyzing dependencies
Fetching podspec for `RNFirebase` from `../node_modules/react-native-firebase`
[!] No podspec found for `RNFirebase` in `../node_modules/react-native-firebase
```
My podfile looks like this:

```
platform :ios, '9.0'

target "DefteriMobileDrc" do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Database'
end
```

**Comment by cmmouritsen** [comment]
Try changing it to this:

```
platform` :ios, '9.0'

target "DefteriMobileDrc" do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Database'
end
```

**Comment by danielcsrs** [comment]
@cmmouritsen thanks! This solved.

**Comment by TCasablancas** [comment]
Worked as hell! Thank u so much, dude!

**Comment by shiundu** [comment]
> Try changing it to this:
> 
> ```
> platform` :ios, '9.0'
> 
> target "DefteriMobileDrc" do
>   pod 'Firebase/Core', '~> 5.3.0'
>   pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
>   pod 'Firebase/Database'
> end
> ```

This should be added to the instructions `/ios` at the end of the path is crucial. Thanks @cmmouritsen!

**Comment by gabrielmoncea** [comment]
I switched from ignite a long time ago and I didn't test the solution. I'll close this issue as I see the solution presented worked for everybody else who had the same problem.

I'm sorry I didn't reply to the first message,  somehow I missed it.

**Comment by Duya3fithou** [comment]
> Try changing it to this:
> 
> ```
> platform` :ios, '9.0'
> 
> target "DefteriMobileDrc" do
>   pod 'Firebase/Core', '~> 5.3.0'
>   pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
>   pod 'Firebase/Database'
> end
> ```

Tks you verymuch

**Comment by Dhanush623** [comment]
> Try changing it to this:
> 
> ```
> platform` :ios, '9.0'
> 
> target "DefteriMobileDrc" do
>   pod 'Firebase/Core', '~> 5.3.0'
>   pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
>   pod 'Firebase/Database'
> end
> ```

This works for me

**Comment by luthfilq** [comment]
> Try changing it to this:
> 
> ```
> platform` :ios, '9.0'
> 
> target "DefteriMobileDrc" do
>   pod 'Firebase/Core', '~> 5.3.0'
>   pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
>   pod 'Firebase/Database'
> end
> ```

I still have the issue

**Comment by AsmaTidafi** [comment]
the solution for me was:
`pod 'RNFirebase', :path => '../node_modules/@react-native-firebase/analytics'`
instead of:
`pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'`
