### ISSUE TITLE
Error add firebase plugin 

### ISSUE THREAD

**Issue by jeancabral** [stoneman1/ignite-firebase#6]
Hi! I have got below error, when add firebase plugin in my Ignite Project

DEPRECATION WARNING: addPluginComponentExample called with 'FirebaseExample.js' and no .ejs extension. Add .ejs to your template filename when calling this function.
Cannot read property 'includes' of undefined

**Comment by stoneman1** [comment]
Hello 
Sorry for the long wait. This plugin have not been updated for a long time. I will try to do it as soon as possible. Starting with making myself a Kanban board for 1.0.0 version.

**Comment by filipef101** [comment]
So its not working? was planning to use this tomorrow

**Comment by filipef101** [comment]
@stoneman1 Does this work or should I manually install firebase? thanks for the work btw

**Comment by stoneman1** [comment]
@filipef101 Do it manually for now. Trying to find time to update this.
